[package]
name = "muadb-util"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { version = "0.4", features = ["max_level_debug", "release_max_level_warn"] }
auto_impl = "1.2.0"
colored = "2.1.0"